name: palestine_filter
description: Apply Palestine Filter to Your Images.

version: 1.1.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # images
  image_picker: ^0.7.4
  image_gallery_saver: '^1.6.9'
  permission_handler: ^7.1.0
  # misc
  fluttertoast: ^8.0.6
  url_launcher: ^6.0.3
  share: ^2.0.1
  easy_localization: ^3.0.0
  # icons
  cupertino_icons: ^1.0.2
  community_material_icon: ^5.9.55
  # ui
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/palestine-icon.jpg"
  image_path_android: "assets/images/palestine-icon-android.png"

flutter:
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/lang/




